pipeline:
  name: Maven-POC-CI
  identifier: MavenPOCCI
  projectIdentifier: default_project
  orgIdentifier: default
  description: Maven CI pipeline that installs Maven and JDK on microdnf-based local delegate
  stages:
    - stage:
        name: Echo-Test-CI
        identifier: EchoTestCI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "excuting pipeline"
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: testGitHubconnector
        build: <+input>
